### ISSUE TITLE
Invert regular expression?

### ISSUE THREAD

**Issue by Simran-B** [mathiasbynens/regenerate#34]
I wonder if it's possible to negate the resulting regexp in regenerate.

One could apparently use negative look-ahead (like `(?!expr)`), but it is said to perform bad. One could also invert the result of `regexp.test(str)` but it might not be ideal either.

How would I go about to "flip" the ranges? Ideally, there would be a built-in method `.invert()`. Another possible approach would be to add the entire range of Unicode characters, then use `.remove()` and `.removeRange()` on that.

**Comment by mathiasbynens** [comment]
```js
const allUnicode = regenerate().addRange(0x000000, 0x10FFFF);

const mySet = regenerate(0x1234, 0x5678); // your stuff here
const myInvertedSet = allUnicode.clone().remove(mySet);
```
