### ISSUE TITLE
Non-minimal regex when adding a second range lower than the first

### ISSUE THREAD

**Issue by Seb35** [mathiasbynens/regenerate#37]
With the specific following instructions, regenerate produces a non-minimal (but correct) regex:
```js
regenerate().addRange( 99, 100 ).addRange( 65, 99 ).toString()
'[cdA-c]'
```
By switching the order, we have a correct minimal regex:
```js
regenerate().addRange( 65, 99 ).addRange( 99, 100 ).toString()
'[A-d]'
```
Playing a bit with the boundaries, it seems it only occur when the end of the second range is exactly the same as the start of the first range.

**Comment by mathiasbynens** [comment]
Good catch. Looks like we have an off-by-one somewhere. Patches welcome!
