### ISSUE TITLE
Incorrect optimization in surrogateMappings

### ISSUE THREAD

**Issue by Dantist** [mathiasbynens/regenerate#42]
The surrogate pair of `0x1F610` is `\uD83D\uDE10` and it got lost during some RegExp optimizations.
Consider this test case:

```
const set = regenerate().addRange(0x1F000, 0x1F1FF).addRange(0x1F300, 0x1F5FF).add(0x1F610);
const testChar = String.fromCodePoint(0x1F610);
```
The RegExp in Unicode mode is correct:
```
console.log(set.toRegExp('u'));    // /[\u{1F000}-\u{1F1FF}\u{1F300}-\u{1F5FF}\u{1F610}]/u
testChar.match(set.toRegExp('u')); // match found
```
The RegExp in "legacy" mode is incorrect (missing surrogate pair for `0x1F610`):
```
console.log(set.toRegExp());    // /[\uD83C\uD83D][\uDC00-\uDDFF\uDF00-\uDFFF]/
testChar.match(set.toRegExp()); // null
```

I know that patches are welcome, but I don't have spare time right now. Will look into the source code later :-)

**Comment by mathiasbynens** [comment]
I cannot reproduce the issue with your provided test case with regenerate v1.4.2:

```js
const regenerate = require('regenerate');

const set = regenerate().addRange(0x1F000, 0x1F1FF).addRange(0x1F300, 0x1F5FF).add(0x1F610);
const testChar = '\u{1F610}';

console.log(set.toRegExp());
// → /\uD83C[\uDC00-\uDDFF\uDF00-\uDFFF]|\uD83D[\uDC00-\uDDFF\uDE10]/
// and not /[\uD83C\uD83D][\uDC00-\uDDFF\uDF00-\uDFFF]/ like in your report
console.log(testChar.match(set.toRegExp())); // null
```

Are you using an outdated version of `regenerate`?

**Comment by Dantist** [comment]
> Are you using an outdated version of `regenerate`?   

Oh, dear. Confirm that. 

This was v1.4.1 that had the issue: https://jsfiddle.net/e30Lts5g/
v1.4.2 is working fine: https://jsfiddle.net/e30Lts5g/1/

Thank you for the tool, sorry for the disturbance! :)
